name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "3.1", ruby: "3.1", os: ubuntu-latest }
          - { name: "3.2", ruby: "3.2", os: ubuntu-latest }
          - { name: "3.3", ruby: "3.3", os: ubuntu-latest }
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: npm test
      - run: npm run lint
      - run: npm run rbtest
      - run: npm run rblint

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true
